require("angold.plugins-setup") -- should be at the top
require("angold.core.options")
require("angold.core.keymaps")
require("angold.core.colorscheme")

require("angold.plugins.comment")
require("angold.plugins.web-devicons")
require("angold.plugins.nvim-tree")
require("angold.plugins.telescope")
require("angold.plugins.treesitter")
require("angold.plugins.nvim-cmp")
require("angold.plugins.lspconfig")
require("angold.plugins.colorizer")
require("angold.plugins.barbar")
require("angold.plugins.lspsaga")
require("angold.plugins.gitsigns")
require("angold.plugins.toggleterm")
require("angold.plugins.navigator")
